(function(){
'use strict';
const KEY='loadcalcprox_standard_dwelling_2023_v1';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number(v).toLocaleString('en-US',{maximumFractionDigits:0}), va=v=>fmt(v)+' VA';
const row=(label,extra={})=>({label,qty:'',va:'',...extra});
function fresh(){return {version:3,projectName:'',projectNumber:'',projectAddress:'',projectCityState:'',voltage:'240',sqft:'',small:'',laundry:'',applianceMotor:'',evManaged:false,evManagedMax:'',reportType:'branded',reportLayout:'full',cooking:[row('Range'),row('Wall Oven'),row('Cooktop')],dryers:[row('Electric Dryer')],appliances:['Refrigerator','Freezer','Dishwasher','Disposal','Range Hood','Garage Door Opener','Microwave','Bath Fan','Water Heater'].map(label=>row(label,{fixed:true,quarterHP:false})),motors:[row('Motor / Pump')],continuous:[row('EV Charger',{ev:true,factor:1}),row('Additional Continuous Load at 100%',{factor:1}),row('Additional Continuous Load at 125%',{factor:1.25})],hvac:[{mode:'',cool:'',heat:''}]};}
let state=fresh(),result,saved=null,promptOpen=false;
const scalars=['projectName','projectNumber','projectAddress','projectCityState','voltage','sqft','small','laundry','applianceMotor','evManagedMax','reportType','reportLayout'];
const groups=['cooking','dryers','appliances','motors','continuous'];
function rowHTML(r,i,g){const name=esc(r.label||'Load '+(i+1));return `<div class="load-row" data-group="${g}" data-index="${i}"><div class="description-cell"><input class="description" data-key="label" aria-label="${name} description" value="${name}" maxlength="120">${g==='continuous'?`<small class="row-note">${r.ev?'7,200 VA minimum or nameplate, whichever is larger':r.factor===1?'Continuous — 100%':'Continuous — 125%'}</small>`:''}</div><label><span class="mobile-label">Qty</span><input data-key="qty" type="number" min="0" step="1" inputmode="numeric" placeholder="Qty" aria-label="${name} quantity" value="${esc(r.qty)}"></label><label><span class="mobile-label">${r.ev?'Nameplate VA':'VA each'}</span><input data-key="va" type="number" min="0" step="any" inputmode="decimal" placeholder="${r.ev?'Nameplate VA':'VA'}" aria-label="${name} ${r.ev?'nameplate VA':'VA each'}" value="${esc(r.va)}"></label><output data-output="${g}-${i}" data-label="Connected VA"></output>${g==='cooking'?`<output data-used-output="${i}" data-label="VA Used"></output>`:''}</div>`;}
function groupHead(g){return '<div class="load-head '+(g==='cooking'?'cooking-head':'')+'"><span>Load Description</span><span>Qty</span><span>VA Each</span><span>Connected VA</span>'+(g==='cooking'?'<span>VA Used</span>':'')+'</div>';}
function renderGroup(g){if(g==='continuous'){$('evRows').innerHTML=groupHead(g)+state[g].map((r,i)=>r.ev?rowHTML(r,i,g):'').join('');$('continuous100Rows').innerHTML=groupHead(g)+state[g].map((r,i)=>!r.ev&&r.factor===1?rowHTML(r,i,g):'').join('');$('continuous125Rows').innerHTML=groupHead(g)+state[g].map((r,i)=>!r.ev&&r.factor!==1?rowHTML(r,i,g):'').join('');return;}$(g+'Rows').innerHTML=groupHead(g)+state[g].map((r,i)=>rowHTML(r,i,g)).join('');}
function renderHVAC(){ $('hvacRows').innerHTML=state.hvac.map((h,i)=>`<div class="hvac-system" data-group="hvac" data-index="${i}"><div class="system-heading"><h3>HVAC System ${i+1}</h3></div><label class="mode-label">Operating Arrangement<select data-key="mode"><option value="">Select arrangement</option><option value="noncoincident" ${h.mode==='noncoincident'?'selected':''}>Cooling OR heating — cannot operate together</option><option value="simultaneous" ${h.mode==='simultaneous'?'selected':''}>Heat pump / cooling AND heat can operate together</option></select></label><div class="load-head"><span>Load Description</span><span></span><span>Total VA</span><span>Load VA</span></div>${[['cool','Cooling / Heat Pump'],['heat','Heating / Supplemental Heat']].map(([key,label])=>`<div class="hvac-entry"><label for="hvac-${i}-${key}">${label}</label><input id="hvac-${i}-${key}" type="number" min="0" step="any" inputmode="decimal" data-key="${key}" aria-label="System ${i+1} ${label} VA" placeholder="VA" value="${esc(h[key])}"><output data-hvac-output="${i}-${key}"></output></div>`).join('')}</div>`).join('');}

function renderEvManagedPanel(){const evs=state.continuous.filter(r=>r.ev),complete=evs.filter(r=>Number(r.qty)>0&&Number(r.va)>0),partial=evs.some(r=>(Number(r.qty)>0)!==(Number(r.va)>0)),enabled=complete.length>0&&!partial;if(!enabled)state.evManaged=false;$('evManaged').disabled=!enabled;$('evManaged').checked=state.evManaged;$('evManagedField').hidden=!state.evManaged;$('evManagedMax').disabled=!state.evManaged;$('evManagementHelp').textContent=enabled?'Check this box when the entered EV chargers share one energy-management system.':'Enter an EV charger quantity and nameplate VA to enable energy management.';}
function render(){state.appliances.forEach(r=>{r.fixed=true;});scalars.forEach(k=>$(k).value=state[k]);groups.forEach(renderGroup);renderHVAC();renderEvManagedPanel();update(false);}
function line(label,value,total=false){return `<div${total?' class="total"':''}><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function display(value){return result.touched?va(value):'—';}
function update(save=true){
 result=StandardEngine.calculate(state);
 $('floorVA').textContent=Number(state.sqft)>0?va(Number(state.sqft)*3):'';$('smallVA').textContent=Number(state.small)>0?va(Number(state.small)*1500):'';$('laundryVA').textContent=Number(state.laundry)>0?va(Number(state.laundry)*1500):'';
 groups.forEach(g=>state[g].forEach((r,i)=>{const el=document.querySelector(`[data-output="${g}-${i}"]`);if(el)el.textContent=Number(r.qty)>0&&Number(r.va)>0?fmt(Number(r.qty)*Number(r.va)):'';}));
 $('generalSummary').innerHTML=line('Connected General Load',display(result.generalConnected))+line('First 3,000 VA at 100%',display(result.demand.first))+line('3,001–120,000 VA at 35%',display(result.demand.middle))+line('Remainder Over 120,000 VA at 25%',display(result.demand.last))+line('General Demand Load',display(result.demand.first+result.demand.middle+result.demand.last),true);
 state.cooking.forEach((r,i)=>{const el=document.querySelector(`[data-used-output="${i}"]`);if(el)el.textContent=Number(r.qty)>0&&Number(r.va)>0?fmt(result.cooking.rows[i].used):'';});
 $('cookingSummary').innerHTML=line('Connected Cooking Load',display(result.cooking.connected))+line(result.cooking.method,display(result.cooking.total),true);
 $('dryerSummary').innerHTML=line('Dryer Demand ('+fmt(StandardEngine.dryerFactor(result.dryerCount)*100)+'%)',display(result.dryers),true);
 $('applianceSummary').innerHTML=line('Qualifying Fixed Appliance Quantity',result.touched?fmt(result.eligibleCount):'—')+line('Appliance Demand ('+(result.eligibleCount>=4?'75% qualifying / 100% other':'100%')+')',display(result.appliances),true);
 state.hvac.forEach((h,i)=>['cool','heat'].forEach(k=>{const el=document.querySelector(`[data-hvac-output="${i}-${k}"]`);if(el)el.textContent=Number(h[k])>0?fmt(Number(h[k])):'';}));
 $('hvacSummary').innerHTML=result.hvacModes.map((h,i)=>line('System '+(i+1)+': '+h.label,display(h.base))).join('')+line('HVAC Load Before Motor Addition',display(result.hvac),true);
 $('motorSummary').innerHTML=line('Additional Motor Loads at 100%',display(result.motorBase))+line('Largest Applicable Motor',display(result.largestMotor))+line('Largest Motor Addition at 25%',display(result.motorAdder),true);
 $('evSummary').innerHTML=line('Connected EV Load',display(result.evConnected))+(result.managedEvCount?line('Combined EV Energy Management Maximum',result.touched&&Number(state.evManagedMax)>0?va(state.evManagedMax):'Incomplete'):'')+line('EV Load Used',display(result.evLoadUsed),true);
 $('continuous100Summary').innerHTML=line('Additional Continuous Loads at 100%',display(result.continuous100),true);
 $('continuous125Summary').innerHTML=line('Additional Continuous Loads at 125%',display(result.continuous125),true);
 const valid=result.touched&&!result.errors.length;
 $('validation').hidden=!result.errors.length;$('validation').innerHTML='<ul>'+result.errors.map(e=>'<li>'+esc(e)+'</li>').join('')+'</ul>';
 $('finalSummary').innerHTML=line('Total Calculated Load',valid?va(result.total):result.touched?'Incomplete':'—',true)+line('Calculated Service Load',valid?result.amps.toLocaleString('en-US',{maximumFractionDigits:1})+' A':result.touched?'Incomplete':'—',true);
 $('floatingAmps').textContent=valid?result.amps.toLocaleString('en-US',{maximumFractionDigits:1})+' A':result.touched?'Incomplete':'—';
 if(save&&!promptOpen){try{const meaningful=result.touched||scalars.slice(0,4).some(k=>state[k]);if(meaningful){localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='Saved on this device.';}else{localStorage.removeItem(KEY);$('saveStatus').textContent='';}}catch{$('saveStatus').textContent='This browser could not save the calculation. Keep this page open or print your report.';}}
}
document.addEventListener('input',event=>{const el=event.target;if((el.id==='small'||el.id==='laundry'||el.dataset.key==='qty')&&el.value!==''&&Number(el.value)<=0)el.value='';if(el.id==='evManaged'){state.evManaged=el.checked;renderEvManagedPanel();update();return;}if(scalars.includes(el.id)){state[el.id]=el.value;update();return;}const parent=el.closest('[data-group]');if(parent&&el.dataset.key){const g=parent.dataset.group,r=state[g][Number(parent.dataset.index)];r[el.dataset.key]=el.type==='checkbox'?el.checked:el.value;if(g==='continuous'&&r.ev)renderEvManagedPanel();update();}});
document.addEventListener('change',event=>{if(event.target.tagName==='SELECT'||event.target.type==='checkbox')event.target.dispatchEvent(new Event('input',{bubbles:true}));});
function removeContinuousType(predicate,message){const indexes=state.continuous.map((r,i)=>predicate(r)?i:-1).filter(i=>i>=0);if(!indexes.length)return;const index=indexes[indexes.length-1],r=state.continuous[index];if((Number(r.qty)||Number(r.va))&&!confirm(message))return;state.continuous.splice(index,1);renderGroup('continuous');update();}
document.addEventListener('click',event=>{const add=event.target.closest('[data-add]'),removeLast=event.target.closest('[data-remove-last]'),addEv=event.target.closest('[data-add-ev]'),removeEv=event.target.closest('[data-remove-ev]'),add100=event.target.closest('[data-add-continuous-100]'),remove100=event.target.closest('[data-remove-continuous-100]'),add125=event.target.closest('[data-add-continuous-125]'),remove125=event.target.closest('[data-remove-continuous-125]');if(addEv){const firstOther=state.continuous.findIndex(r=>!r.ev),evNumber=state.continuous.filter(r=>r.ev).length+1;state.continuous.splice(firstOther<0?state.continuous.length:firstOther,0,row('EV Charger '+evNumber,{ev:true,factor:1}));renderGroup('continuous');renderEvManagedPanel();update();return;}if(removeEv){const evIndexes=state.continuous.map((r,i)=>r.ev?i:-1).filter(i=>i>=0);if(evIndexes.length<=1)return;const index=evIndexes[evIndexes.length-1],r=state.continuous[index];if((Number(r.qty)||Number(r.va))&&!confirm('Remove the last EV charger and its entered values?'))return;state.continuous.splice(index,1);renderGroup('continuous');renderEvManagedPanel();update();return;}if(add100){state.continuous.push(row('Additional Continuous Load at 100%',{factor:1}));renderGroup('continuous');update();return;}if(remove100){removeContinuousType(r=>!r.ev&&r.factor===1,'Remove the last 100% continuous load and its entered values?');return;}if(add125){state.continuous.push(row('Additional Continuous Load at 125%',{factor:1.25}));renderGroup('continuous');update();return;}if(remove125){removeContinuousType(r=>!r.ev&&r.factor!==1,'Remove the last 125% continuous load and its entered values?');return;}if(add){const g=add.dataset.add;state[g].push(row('Additional '+g.replace(/s$/,''),g==='appliances'?{fixed:true,quarterHP:false}:{}));renderGroup(g);update();}if(removeLast){const g=removeLast.dataset.removeLast;if(!state[g].length)return;const r=state[g][state[g].length-1];if((Number(r.qty)||Number(r.va)||Number(r.cool)||Number(r.heat))&&!confirm('Remove the last item and its entered values?'))return;state[g].pop();g==='hvac'?renderHVAC():renderGroup(g);update();}});
function reset(){state=fresh();render();update();}
 $('addHvac').onclick=()=>{state.hvac.push({mode:'',cool:'',heat:''});renderHVAC();update();};
 $('reset').onclick=()=>{if(confirm('Start a new calculation? This clears the current entries for this calculator.'))reset();};
 $('mainSite').onclick=()=>location.href='../index.html';$('calculators').onclick=()=>location.href='../member-dashboard.html';
 $('continue').onclick=()=>{state=saved;promptOpen=false;$('restore').close();render();};$('startNew').onclick=()=>{promptOpen=false;$('restore').close();reset();};
 $('restore').addEventListener('cancel',e=>e.preventDefault());
 function printRow(label,qty,each,total,cls=''){return `<tr class="${cls}"><td>${esc(label)}</td><td>${qty?esc(qty):''}</td><td>${each?fmt(each):''}</td><td>${fmt(total)}</td></tr>`;}
 function section(title){return `<tr class="section"><td colspan="4">${esc(title)}</td></tr>`;}
 function loadRows(g){return state[g].filter(r=>Number(r.qty)>0&&Number(r.va)>0).map(r=>printRow(r.label+(g==='appliances'&&r.fixed?' (fixed)':''),r.qty,r.va,Number(r.qty)*Number(r.va))).join('');}
 function buildReport(){
  update(false);const r=result;let html=section('General Loads')+printRow('Square Footage × 3 VA',state.sqft,3,Number(state.sqft)*3)+printRow('Small Appliance Circuits',state.small,1500,Number(state.small)*1500)+printRow('Laundry Circuits',state.laundry,1500,Number(state.laundry)*1500)+printRow('Connected General Load','','',r.generalConnected,'total')+printRow('First 3,000 VA at 100%','','',r.demand.first)+printRow('3,001–120,000 VA at 35%','','',r.demand.middle);
  if(r.demand.last)html+=printRow('Remainder Over 120,000 VA at 25%','','',r.demand.last);
  html+=printRow('General Demand Load','','',r.demand.first+r.demand.middle+r.demand.last,'total');
  if(r.cooking.total)html+=section('Cooking Appliances')+state.cooking.map(x=>Number(x.qty)>0&&Number(x.va)>0?printRow(x.label,x.qty,x.va,Number(x.qty)*Number(x.va)):'').join('')+printRow('Combined '+r.cooking.method,'','',r.cooking.total,'total');
  if(r.dryers)html+=section('Electric Dryers')+loadRows('dryers')+printRow('Minimum-adjusted load × '+fmt(StandardEngine.dryerFactor(r.dryerCount)*100)+'%','','',r.dryers,'total');
  if(r.appliances)html+=section('Appliance Loads')+loadRows('appliances')+printRow('Qualifying fixed appliances: '+r.eligibleCount+'; '+(r.eligibleCount>=4?'75% qualifying / 100% other':'100%')+' demand','','',r.appliances,'total');
  if(r.hvac){html+=section('HVAC Loads');state.hvac.forEach((h,i)=>{if(Number(h.cool)>0)html+=printRow('System '+(i+1)+' Cooling / Heat Pump Input','','',Number(h.cool));if(Number(h.heat)>0)html+=printRow('System '+(i+1)+' Heating Input','','',Number(h.heat));if(r.hvacModes[i].base)html+=printRow('System '+(i+1)+': '+r.hvacModes[i].label,'','',r.hvacModes[i].base,'total');});html+=printRow('HVAC Load Used','','',r.hvac,'total');}
  if(r.motorBase||r.motorAdder)html+=section('Motors')+loadRows('motors')+printRow('Largest applicable motor '+va(r.largestMotor)+' × 25%','','',r.motorAdder,'total');
  if(r.evLoadUsed){html+=section('EV Charging Loads');state.continuous.filter(x=>x.ev&&Number(x.qty)>0&&Number(x.va)>0).forEach(x=>{if(state.evManaged)html+=printRow(x.label+' — EV energy-managed',x.qty,Number(x.va),Number(x.qty)*Number(x.va));else{const each=Math.max(7200,Number(x.va));html+=printRow(x.label+' — 7,200 VA minimum or nameplate',x.qty,each,Number(x.qty)*each);}});if(r.managedEvCount)html+=printRow('Combined EV Energy Management Maximum','','',Number(state.evManagedMax),'total');html+=printRow('EV Load Used','','',r.evLoadUsed,'total');}
  if(r.continuous100){html+=section('Additional Continuous Loads at 100%');state.continuous.filter(x=>!x.ev&&x.factor===1&&Number(x.qty)>0&&Number(x.va)>0).forEach(x=>{html+=printRow(x.label,x.qty,Number(x.va),Number(x.qty)*Number(x.va));});html+=printRow('Additional Continuous Loads at 100%','','',r.continuous100,'total');}
  if(r.continuous125){html+=section('Additional Continuous Loads at 125%');state.continuous.filter(x=>!x.ev&&x.factor!==1&&Number(x.qty)>0&&Number(x.va)>0).forEach(x=>{html+=printRow(x.label+' × 125%',x.qty,Number(x.va),Number(x.qty)*Number(x.va)*1.25);});html+=printRow('Additional Continuous Loads at 125%','','',r.continuous125,'total');}
  html+=printRow('TOTAL CALCULATED LOAD','','',r.total,'total');
  const warning=r.errors.length?'<p class="validation">INCOMPLETE CALCULATION: '+r.errors.map(esc).join(' ')+'</p>':'';
  $('printReport').className=state.reportLayout==='compact'?'compact':'';
  $('printReport').innerHTML=`<div class="report-header"><div><h1>Standard Method Dwelling Load Calculation</h1><p>NEC 2023 | Version 1.0</p></div>${state.reportType==='branded'?'<div class="print-brand"><span class="print-brand-main">LoadCalc</span><span class="print-brand-accent">Pro X</span></div>':''}</div><div class="report-meta">${['projectName','projectNumber','projectAddress','projectCityState'].map((k,i)=>state[k]?'<div><strong>'+['Project','Project Number','Address','City / State'][i]+':</strong> '+esc(state[k])+'</div>':'').join('')}</div>${warning}<table><colgroup><col style="width:61%"><col style="width:9%"><col style="width:14%"><col style="width:16%"></colgroup><thead><tr><th>Load Description / Calculation</th><th>Qty</th><th>VA Each</th><th>Load VA</th></tr></thead><tbody>${html}</tbody></table><div class="report-result">Calculated Service Load: ${r.errors.length||!r.touched?'Incomplete':r.amps.toLocaleString('en-US',{maximumFractionDigits:1})+' A'} &nbsp; | &nbsp; ${esc(state.voltage)} V</div><p class="report-foot">Single dwelling, two ungrounded conductors. NEC 2023: 220.42, 220.52–220.55, 220.57, 220.60, 430.24 and 625.42. Equipment entered at nameplate / applicable motor load; one largest-motor addition. Conductor, overcurrent protection and neutral sizing are separate.</p>`;
 }
 $('print').onclick=()=>{update(false);if(result.errors.length||!result.touched){$('validation').hidden=false;if(!result.touched)$('validation').textContent='Enter the dwelling loads before printing.';$('validation').scrollIntoView({behavior:'smooth',block:'center'});return;}buildReport();window.print();};
 window.addEventListener('beforeprint',buildReport);
 try{const parsed=JSON.parse(localStorage.getItem(KEY)||'null');if(parsed&&[1,2,3].includes(parsed.version)&&groups.every(g=>Array.isArray(parsed[g]))&&Array.isArray(parsed.hvac)){const migrated={...fresh(),...parsed,version:3};migrated.evManaged=parsed.evManaged===true||parsed.continuous.some(r=>r.ev&&r.managed);if(!migrated.evManagedMax){const oldManaged=parsed.continuous.find(r=>r.ev&&r.managed&&Number(r.managedVa)>0);migrated.evManagedMax=oldManaged?oldManaged.managedVa:'';}migrated.continuous=migrated.continuous.map(r=>{const copy={...r};if(copy.label==='Other Noncontinuous Load')copy.label='Additional Continuous Load at 100%';if(copy.label==='Additional Continuous Load'&&copy.factor!==1)copy.label='Additional Continuous Load at 125%';delete copy.managed;delete copy.managedVa;return copy;});saved=migrated;}}catch{}
 render();if(saved){promptOpen=true;$('restore').showModal();}
})();
