/* LoadCalcPro X Generator — consolidated runtime authority.
   Loaded after script.js and before print-report.js.
   This replaces the former restore/runtime/bottom/header/section/report helper files. */

/* Meaningful saved calculation + EV row behavior. */
(function(){
'use strict';
function nonBlank(value){return String(value===null||value===undefined?'':value).trim()!==''}
function positiveOrText(value){const text=String(value===null||value===undefined?'':value).trim();if(!text)return false;const number=Number(text);return Number.isFinite(number)?number>0:true}
function hasMeaningfulHvacData(){try{const raw=localStorage.getItem('loadcalcpro_hvac_method_sections_v57');if(!raw)return false;const data=JSON.parse(raw);if(!data||typeof data!=='object')return false;return Object.values(data).some(function(item){if(!item||typeof item!=='object')return false;return positiveOrText(item.qty)||positiveOrText(item.va)})}catch(e){return false}}
window.hasSavedCalculation=function(){const data=(typeof savedState==='function')?savedState():null;if(!data)return false;const project=Object.values(data.project||{}).some(nonBlank);const inputs=Object.entries(data.inputs||{}).some(function(entry){const id=entry[0],value=entry[1];if(id==='q46')return false;return positiveOrText(value)});const motor=data.largestMotor||{};const largestMotor=motor.included===true||positiveOrText(motor.va)||nonBlank(motor.type);const managed=Object.values(data.managedQuantities||{}).some(function(value){return Number(value)>0});return project||inputs||largestMotor||managed||hasMeaningfulHvacData()};
window.rowVA=function(row){const quantity=(typeof positiveQuantity==='function')?positiveQuantity('q'+row):Math.max(0,Math.floor(Number(document.getElementById('q'+row)?.value)||0));const enteredVA=(typeof numberValue==='function')?numberValue('v'+row):Math.max(0,Number(document.getElementById('v'+row)?.value)||0);if(row===43){if(quantity<1||enteredVA<=0)return 0;return quantity*Math.max(enteredVA,7200)}return quantity*enteredVA};
})();

/* Stable HVAC calculation authority. */
(function(){
'use strict';
const original=window.hvacLoadCalculation;if(typeof original!=='function')return;
const METHODS_KEY='loadcalcpro_hvac_selected_methods_v1',DATA_KEY='loadcalcpro_hvac_method_sections_v57',MANAGED_KEY='loadcalcpro_hvac_method_managed_v57',COUNT_KEY='loadcalcpro_hvac_visible_system_counts_v522',HP_SYSTEM_KEY='loadcalcpro_hvac_heatpump_answers_v543';
function readJSON(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||'');return value&&typeof value==='object'?value:fallback}catch(e){return fallback}}
function selected(){const value=readJSON(METHODS_KEY,[]);return Array.isArray(value)?value.filter(m=>['central65','separate40','heatpump'].includes(m)):[]}
function count(method){const counts=readJSON(COUNT_KEY,{});return Math.max(1,Math.min(3,Math.floor(Number(counts[method])||1)))}
function typeFor(kind,index){return kind+(index===1?'':index)}function key(method,type){return method+'_'+type}function item(method,type){return readJSON(DATA_KEY,{})[key(method,type)]||{}}
function qty(method,type){return Math.max(0,Math.floor(Number(item(method,type).qty)||0))}function va(method,type){return Math.max(0,Number(item(method,type).va)||0)}function total(method,type){return qty(method,type)*va(method,type)}
function managedQty(method,type){const q=qty(method,type),raw=readJSON(MANAGED_KEY,{})[key(method,type)],n=raw===true?q:Math.floor(Number(raw)||0);return Math.max(0,Math.min(q,n))}
function remaining(method,type){return Math.max(qty(method,type)-managedQty(method,type),0)*va(method,type)}
function aggregate(method,kind,generator){let value=0;for(let i=1;i<=count(method);i++)value+=(generator?remaining:total)(method,typeFor(kind,i));return value}
function heatFactor(method){if(method!=='separate40')return .65;let units=0;for(let i=1;i<=count(method);i++)units+=qty(method,typeFor('heat',i));return units>=4?.40:.65}
function hpAnswer(index){const answers=readJSON(HP_SYSTEM_KEY,{});return answers[String(index)]||''}
function heatPumpResult(generator){let result={total:0,c:0,h:0};for(let i=1;i<=count('heatpump');i++){const ac=typeFor('ac',i),heat=typeFor('heat',i),serviceC=total('heatpump',ac),serviceH=total('heatpump',heat)*.65,c=(generator?remaining:total)('heatpump',ac),h=(generator?remaining:total)('heatpump',heat)*.65,answer=hpAnswer(i);if(answer==='yes'){result.total+=c+h;result.c+=c;result.h+=h}else if(answer==='no'){if(serviceC>=serviceH){result.total+=c;result.c+=c}else{result.total+=h;result.h+=h}}}return result}
function normalResult(method,generator){const factor=heatFactor(method),serviceC=aggregate(method,'ac',false),serviceH=aggregate(method,'heat',false)*factor,c=aggregate(method,'ac',generator),h=aggregate(method,'heat',generator)*factor;return serviceC>=serviceH?{total:c,c:c,h:0}:{total:h,c:0,h:h}}
window.hvacLoadCalculation=function(){original();let service=0,generator=0,serviceAC=0,generatorAC=0,serviceHeating=0,generatorHeating=0;selected().forEach(method=>{let s,g;if(method==='heatpump'){s=heatPumpResult(false);g=heatPumpResult(true)}else{s=normalResult(method,false);g=normalResult(method,true)}service+=s.total;generator+=g.total;serviceAC+=s.c;generatorAC+=g.c;serviceHeating+=s.h;generatorHeating+=g.h});if(typeof setOutput==='function'){setOutput('e37',serviceAC);setOutput('e38',serviceHeating);setOutput('f37',generatorAC);setOutput('f38',generatorHeating)}return{service,generator,serviceAC,generatorAC,serviceHeating,generatorHeating,method:selected().join(','),multipleHeatTypes:selected().length>1}}
})();

/* Heat-pump per-system answers. */
(function(){
'use strict';
const HP_SYSTEM_KEY='loadcalcpro_hvac_heatpump_answers_v543',LEGACY_HP_KEY='loadcalcpro_hvac_multi_hp_answer_v1';
function readAnswers(){try{const value=JSON.parse(localStorage.getItem(HP_SYSTEM_KEY)||'{}');return value&&typeof value==='object'?value:{}}catch(e){return {}}}
function writeAnswers(value){try{localStorage.setItem(HP_SYSTEM_KEY,JSON.stringify(value));localStorage.setItem(LEGACY_HP_KEY,'yes')}catch(e){}}
function refreshQuestion(index){const answers=readAnswers(),current=answers[String(index)]||'';document.querySelectorAll('.v543-hp-option[data-v543-hp-index="'+index+'"]').forEach(function(button){const chosen=button.dataset.v543HpAnswer===current;button.classList.toggle('selected',chosen);const mark=button.querySelector('.v543-hp-check');if(mark)mark.textContent=chosen?'✓':''})}
document.addEventListener('click',function(event){const button=event.target.closest('.v543-hp-option');if(!button)return;event.preventDefault();event.stopImmediatePropagation();const index=String(button.dataset.v543HpIndex||''),answer=String(button.dataset.v543HpAnswer||'');if(!index||(answer!=='yes'&&answer!=='no'))return;const answers=readAnswers();if(answers[index]===answer)delete answers[index];else answers[index]=answer;writeAnswers(answers);refreshQuestion(index);if(typeof calculate==='function')calculate()},true)
})();

/* Final calculator summary. */
(function(){
'use strict';
function makeRow(label,valueNode,suffix){const row=document.createElement('div');row.className='calculation-summary-row';const labelNode=document.createElement('span');labelNode.textContent=label;const valueWrap=document.createElement('span');valueWrap.appendChild(valueNode);if(suffix)valueWrap.appendChild(document.createTextNode(suffix));row.appendChild(labelNode);row.appendChild(valueWrap);return row}
function syncSummaryValues(){const serviceSource=document.getElementById('serviceTotalVAView'),generatorSource=document.getElementById('generatorTotalVAView'),serviceTarget=document.getElementById('calcSummaryServiceVA'),generatorTarget=document.getElementById('calcSummaryGeneratorVA');if(serviceSource&&serviceTarget)serviceTarget.textContent=serviceSource.textContent||'0';if(generatorSource&&generatorTarget)generatorTarget.textContent=generatorSource.textContent||'0'}
function watch(source){if(!source||!window.MutationObserver)return;new MutationObserver(syncSummaryValues).observe(source,{childList:true,characterData:true,subtree:true})}
function init(){if(document.getElementById('calculationFinalSummary'))return;const q42=document.getElementById('q42'),additionalRow=q42?q42.closest('.load-row'):null,managedCount=document.getElementById('bottomManagedLoadCount'),generatorVA=document.getElementById('generatorTotalVAView'),generatorLine=generatorVA?generatorVA.closest('.total-managed-line'):null;if(!additionalRow||!managedCount||!generatorVA||!generatorLine)return;const summary=document.createElement('div');summary.id='calculationFinalSummary';summary.className='calculation-summary';summary.setAttribute('aria-label','Final calculation summary');const serviceValue=document.createElement('span');serviceValue.id='calcSummaryServiceVA';serviceValue.textContent='0';const generatorValue=document.createElement('span');generatorValue.id='calcSummaryGeneratorVA';generatorValue.textContent='0';summary.appendChild(makeRow('Service Load:',serviceValue,' VA'));summary.appendChild(makeRow('Generator Load:',generatorValue,' VA'));summary.appendChild(makeRow('Managed Quantity:',managedCount,''));const continuousBody=additionalRow.closest('.card-body');if(continuousBody)continuousBody.appendChild(summary);else additionalRow.insertAdjacentElement('afterend',summary);syncSummaryValues();watch(document.getElementById('serviceTotalVAView'));watch(generatorVA)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()
})();

/* Bottom results, header controls, and customer navigation. */
(function(){
'use strict';
function hasEnteredValue(ids){return ids.some(function(id){const el=document.getElementById(id);return !!(el&&String(el.value||'').trim()!=='')})}
function calculationStarted(){const ids=['q5','q6','q7'];for(let row=10;row<=30;row++)ids.push('q'+row,'v'+row);ids.push('q37','v37','q38','v38','q42','v42','q43','v43','q47','v47');if(hasEnteredValue(ids))return true;return !!document.querySelector('.heating-method-choice[aria-pressed="true"],#multipleHvacSystemsChoice[aria-pressed="true"]')}
function generalApplianceStarted(){const ids=['q5','q6','q7'];for(let row=10;row<=30;row++)ids.push('q'+row,'v'+row);return hasEnteredValue(ids)}
function hvacContinuousStarted(){const ids=['q37','v37','q38','v38','q42','v42','q43','v43','q47','v47'];if(hasEnteredValue(ids))return true;return !!document.querySelector('.heating-method-choice[aria-pressed="true"],#multipleHvacSystemsChoice[aria-pressed="true"]')}
function blankZero(id,started){const el=document.getElementById(id);if(!el||started)return;const text=String(el.textContent||'').trim();if(text==='0'||text==='0 A'||text==='0 VA')el.textContent=''}
function blankManagedQuantityZero(){const el=document.getElementById('bottomManagedLoadCount');if(!el)return;if(String(el.textContent||'').trim()==='0')el.textContent=''}
function syncBlankInitialSummaries(){blankZero('generalApplianceService',generalApplianceStarted());blankZero('generalApplianceGenerator',generalApplianceStarted());blankZero('hvacContinuousService',hvacContinuousStarted());blankZero('hvacContinuousGenerator',hvacContinuousStarted());blankZero('calcSummaryServiceVA',calculationStarted());blankZero('calcSummaryGeneratorVA',calculationStarted());blankManagedQuantityZero()}
function syncBottomResults(){const serviceSource=document.getElementById('serviceAmps'),generatorSource=document.getElementById('generatorAmps'),serviceView=document.getElementById('serviceAmpsView'),generatorView=document.getElementById('generatorAmpsView');if(serviceSource&&serviceView)serviceView.textContent=String(serviceSource.textContent||'0 A').trim()||'0 A';if(generatorSource&&generatorView)generatorView.textContent=String(generatorSource.textContent||'0 A').trim()||'0 A';syncBlankInitialSummaries()}
function observe(id){const el=document.getElementById(id);if(!el||!window.MutationObserver)return;new MutationObserver(syncBottomResults).observe(el,{childList:true,characterData:true,subtree:true})}
function trialDashboardUrl(){const trialEmail=localStorage.getItem('loadcalcproTrialEmail'),trialCode=localStorage.getItem('loadcalcproTrialCode');return trialEmail&&trialCode?'../trial-dashboard.html':'../member-dashboard.html'}
function installTrialNavigation(){const actions=document.querySelector('.header-actions');if(!actions)return;const button=Array.from(actions.querySelectorAll('button')).find(b=>{const text=String(b.textContent||'').trim().toLowerCase(),onclick=String(b.getAttribute('onclick')||'').toLowerCase();return text==='available calculators'||text==='calculators'||onclick.includes('member-dashboard.html')});if(!button)return;button.textContent='Calculators';button.removeAttribute('onclick');button.onclick=function(event){if(event){event.preventDefault();event.stopPropagation()}window.location.href=trialDashboardUrl();return false}}
function installPrintControls(){if(document.getElementById('generatorPrintType'))return;const actions=document.querySelector('.header-actions');if(!actions)return;const printButton=Array.from(actions.querySelectorAll('button')).find(button=>String(button.getAttribute('onclick')||'').includes('printCalculation'));if(!printButton)return;const control=document.createElement('div');control.className='generator-print-control';control.innerHTML='<select id="generatorPrintType" aria-label="Generator print type"><option value="branded" selected>Branded Report</option><option value="calculation">Calculation Only</option></select><select id="generatorPrintLayout" aria-label="Generator print layout"><option value="full" selected>Full Width</option><option value="compact">Compact Left</option></select>';actions.insertBefore(control,printButton)}
function enforceHeaderVersion(){const version=document.querySelector('.app-version');if(version&&version.textContent!=='NEC 2023 | Version 1.0')version.textContent='NEC 2023 | Version 1.0'}
function installCustomerHeader(){const title=document.querySelector('.app-title'),actions=document.querySelector('.header-actions');if(title)title.textContent='Generator Optional Method Calculator';enforceHeaderVersion();if(!actions)return;const mainSiteButtons=Array.from(actions.querySelectorAll('button')).filter(button=>{const text=String(button.textContent||'').trim().toLowerCase(),onclick=String(button.getAttribute('onclick')||'').toLowerCase();return button.classList.contains('generator-main-site')||text==='main site'||onclick.includes('../index.html')||onclick.includes('index.html')});let mainSite=mainSiteButtons.shift()||null;mainSiteButtons.forEach(button=>button.remove());if(!mainSite){mainSite=document.createElement('button');mainSite.type='button';actions.insertBefore(mainSite,actions.firstChild)}mainSite.classList.add('generator-main-site');mainSite.textContent='Main Site';mainSite.removeAttribute('onclick');mainSite.onclick=function(event){if(event){event.preventDefault();event.stopPropagation()}window.location.href='../index.html';return false};installTrialNavigation()}
function syncHeaderLabels(){const actions=document.querySelector('.header-actions');if(!actions)return;const printButton=Array.from(actions.querySelectorAll('button')).find(button=>String(button.getAttribute('onclick')||'').includes('printCalculation'));if(printButton)printButton.textContent='Print / PDF';const newButton=Array.from(actions.querySelectorAll('button')).find(button=>String(button.getAttribute('onclick')||'').includes('startNewCalculationFromButton'));if(newButton)newButton.textContent='New Calculation'}
function init(){syncBottomResults();observe('serviceAmps');observe('generatorAmps');document.addEventListener('input',function(){setTimeout(syncBottomResults,0)});document.addEventListener('change',function(){setTimeout(syncBottomResults,0)});document.addEventListener('click',function(){setTimeout(syncBottomResults,0)});installPrintControls();installCustomerHeader();syncHeaderLabels();[0,100,500,1500].forEach(delay=>setTimeout(enforceHeaderVersion,delay));[0,100,500].forEach(delay=>setTimeout(syncBlankInitialSummaries,delay));[100,500].forEach(delay=>setTimeout(installTrialNavigation,delay))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();

/* Section column headers. The HVAC selector is not a load-entry section; only
   actual HVAC System groups receive the six-column load header. */
(function(){
'use strict';
function makeHeader(){const header=document.createElement('div');header.className='v3-column-header section-column-header';header.innerHTML='<span>Description</span><span>Quantity</span><span>VA</span><span>Managed</span><span>Service Load</span><span>Generator Load</span>';return header}
function cardByHeading(text){return Array.from(document.querySelectorAll('main .card')).find(function(card){const heading=card.querySelector('.card-heading');return heading&&String(heading.textContent||'').replace(/\s+/g,' ').trim()===text})||null}
function syncContinuousHeader(){const card=document.querySelector('.continuous-loads-card')||cardByHeading('Continuous Loads');if(!card)return;const body=card.querySelector('.card-body');if(!body)return;let header=body.querySelector(':scope > .section-column-header');if(!header){header=makeHeader();const firstRow=body.querySelector(':scope > .load-row');if(firstRow)body.insertBefore(header,firstRow);else body.prepend(header)}}
function syncHVACHeaders(){const card=cardByHeading('HVAC Loads');const body=card&&card.querySelector('.card-body');if(body){body.querySelectorAll(':scope > .v3-column-header').forEach(function(header){header.remove()})}const root=document.getElementById('v57HvacMethodSections');if(!root)return;root.querySelectorAll('.v522-system-title').forEach(function(title){const group=title.parentElement;if(!group)return;let header=group.querySelector(':scope > .section-column-header');if(!header){header=makeHeader();title.insertAdjacentElement('afterend',header)}else if(header.previousElementSibling!==title){title.insertAdjacentElement('afterend',header)}})}
function sync(){syncContinuousHeader();syncHVACHeaders()}
function scheduleSync(){[0,60,250,600,1200].forEach(function(delay){setTimeout(sync,delay)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scheduleSync,{once:true});else scheduleSync();
document.addEventListener('click',function(event){if(event.target.closest('.heating-method-choice,#multipleHvacSystemsChoice,.v522-add-system,.v523-remove-system,.v57-hp-option'))scheduleSync()});document.addEventListener('change',function(event){if(event.target.closest('#v57HvacMethodSections,.heating-method-panel'))scheduleSync()});window.syncGeneratorSectionColumnHeaders=sync;
})();

/* Screen checkpoint totals. */
(function(){
'use strict';
function outputNumber(id){const el=document.getElementById(id);if(!el)return 0;const n=Number(String(el.textContent||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0}
function inputNumber(id){const el=document.getElementById(id);const n=Number(el?el.value:0);return Number.isFinite(n)?n:0}
function displayNumber(value){const n=Math.round(Number(value)||0);return n.toLocaleString('en-US')}
function generalLoadTotal(){return Math.max(inputNumber('q5'),0)*3+Math.max(Math.floor(inputNumber('q6')),0)*1500+Math.max(Math.floor(inputNumber('q7')),0)*1500}
function applianceColumnTotal(prefix){let total=0;for(let row=10;row<=30;row++)total+=outputNumber(prefix+row);return total}
function generalApplianceTotals(){const general=generalLoadTotal();return{service:general+applianceColumnTotal('e'),generator:general+applianceColumnTotal('f')}}
function hvacContinuousTotals(){return{service:outputNumber('e44')+outputNumber('e45'),generator:outputNumber('f44')+outputNumber('f45')}}
function ensureCalculatorTotals(){const demand=document.getElementById('v3DemandCard');if(demand){const body=demand.querySelector('.card-body');if(body&&!document.getElementById('generalApplianceTotalRow')){const row=document.createElement('div');row.id='generalApplianceTotalRow';row.className='demand-row checkpoint-total-row';row.innerHTML='<span class="demand-description">Total General + Appliance Load</span><span id="generalApplianceService" class="demand-service"></span><span id="generalApplianceGenerator" class="demand-generator"></span>';const first=body.querySelector('.demand-row');if(first)body.insertBefore(row,first);else body.appendChild(row)}}const continuous=document.querySelector('.continuous-loads-card .card-body');if(continuous&&!document.getElementById('hvacContinuousTotalRow')){const row=document.createElement('div');row.id='hvacContinuousTotalRow';row.className='checkpoint-total-box';row.innerHTML='<div class="checkpoint-total-label">Total HVAC + Continuous Load</div><div class="checkpoint-total-values"><div><span>Service Load</span><strong id="hvacContinuousService"></strong></div><div><span>Generator Load</span><strong id="hvacContinuousGenerator"></strong></div></div>';const finalSummary=document.getElementById('calculationFinalSummary');if(finalSummary&&finalSummary.parentElement===continuous)continuous.insertBefore(row,finalSummary);else continuous.appendChild(row)}}
function updateCalculatorTotals(){ensureCalculatorTotals();const ga=generalApplianceTotals(),hc=hvacContinuousTotals(),map={generalApplianceService:ga.service,generalApplianceGenerator:ga.generator,hvacContinuousService:hc.service,hvacContinuousGenerator:hc.generator};Object.entries(map).forEach(([id,value])=>{const el=document.getElementById(id);if(el)el.textContent=displayNumber(value)})}
const originalCalculate=window.calculate;if(typeof originalCalculate==='function'&&!window.__generatorCheckpointCalculateWrapped){window.calculate=function(){const result=originalCalculate.apply(this,arguments);updateCalculatorTotals();return result};window.__generatorCheckpointCalculateWrapped=true}
function init(){ensureCalculatorTotals();updateCalculatorTotals();setTimeout(updateCalculatorTotals,0);setTimeout(updateCalculatorTotals,150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else init();
})();